swagger: "2.0"
info:
  description: "Cloud Endpoints DNS"
  title: "Cloud Endpoints DNS"
  version: "1.0.0"
paths: {}
host: "frontend.endpoints.fleets-argocd-demo.cloud.goog"
x-google-endpoints:
- name: "frontend.endpoints.fleets-argocd-demo.cloud.goog"
  target: "35.244.207.147"
