apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd
  name: argocd-fleet-plugin-secrets-role
rules:
- apiGroups: [""] # Core API group
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: argocd
  name: argocd-fleet-plugin-secrets-rolebinding
subjects:
- kind: ServiceAccount
  name: argocd-fleet-plugin
  namespace: argocd
roleRef:
  kind: Role 
  name: argocd-fleet-plugin-secrets-role 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-plugin
  namespace: argocd
data:
  token: "supersecret"
  baseUrl: "http://fleet-plugin.argocd.svc.cluster.local:8888"
  FLEET_PROJECT_NUMBER: "143611928672"
  PORT: ":4356"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-fleet-plugin
  namespace: argocd
spec:
  replicas: 1 # can be scaled up
  selector:
    matchLabels:
      app.kubernetes.io/name: fleet-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fleet-plugin
    spec:
      serviceAccount: argocd-fleet-plugin
      serviceAccountName: argocd-fleet-plugin
      containers:
      - name: argocd-fleet-plugin
        image: us-central1-docker.pkg.dev/fleets-argocd-demo/argocd-fleet-plugin-repo/argocd-fleet-plugin@sha256:8586c23576077624910a28655b6383016fdd78a38aed4a8768694f0d9e984d2f
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: fleet-plugin
        ports:
          - containerPort: 4356
            name: http
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
      volumes:
        - name: token
          secret:
            secretName: fleet-plugin
---
apiVersion: v1
kind: Service
metadata:
  name: fleet-plugin
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: fleet-plugin
  ports:
  - name: http
    port: 8888
    targetPort: 4356
---
# This secret lives with the plugin, and is mounted into the plugin container. The ApplicationSet controller must be
# configured with the exact same secret.
apiVersion: v1
kind: Secret
metadata:
  name: fleet-plugin
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
stringData:
  token: 'supersecret'
