apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-fleet-plugin
  namespace: argocd
  annotations:
    iam.gke.io/gcp-service-account: argocd-fleet-admin@fleets-argocd-demo.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: argocd-fleet-admin@fleets-argocd-demo.iam.gserviceaccount.com
  name: argocd-server
  namespace: argocd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: argocd-fleet-admin@fleets-argocd-demo.iam.gserviceaccount.com
  name: argocd-application-controller
  namespace: argocd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: argocd-fleet-admin@fleets-argocd-demo.iam.gserviceaccount.com
  name: argocd-applicationset-controller
  namespace: argocd